config/routes.rb
Socialnamegame::Application.routes.draw do

  match 'game(/:action(/:id))', controller: :game

  match "/auth/:provider/callback" => "sessions#create"

  match "/signout" => "sessions#destroy", :as => :signout

  match '/delete_account' => "home#delete_account", :as => :delete_account

  root :to => "home#index"
end

app/models/authentication.rb
class Authentication < ActiveRecord::Base

  belongs_to :user

  attr_accessible :uid, :provider, :refresh_token, :token, :info, :user_id
end

app/models/person.rb
class Person < ActiveRecord::Base

  belongs_to :user

  attr_accessible :name, :photo_url, :provider, :user_id, :user
end

app/models/score.rb
class Score < ActiveRecord::Base

  belongs_to :user

  attr_accessible :value, :created_at, :user_id
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :photo_url

  has_many :authentications
  has_many :persons

  def self.find_from_omniauth(auth)
    auth = Authentication.find_by_provider_and_uid(auth["provider"],
                                                   auth["uid"])
    auth.user if auth
  end

  def self.create_with_omniauth(auth)
    u = User.create(name: auth["info"]["name"],
                    photo_url: auth["info"]["image"])
    a = Authentication.new(provider: auth["provider"],
                          uid: auth["uid"],
                          token: auth["credentials"]["token"],
                          refresh_token: auth["credentials"]["secret"],
                          user_id: u.id)
    case a.provider
    when 'facebook'
      a.info = auth["info"]["nickname"]
      w = FacebookWorker.new
    when 'twitter'
      a.info = auth["info"]["nickname"]
      w = TwitterWorker.new
    when 'linkedin'
      a.info = auth["info"]["nickname"]
      w = LinkedinWorker.new
    when 'salesforce'
      a.info = auth["credentials"]["instance_url"]
      w = SalesforceWorker.new
    end
    a.save

    w.perform({ 'user' => u.id }) if w
    u
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :redirect_https

  def redirect_https
    redirect_to :protocol => "https://" unless request.ssl? or Rails.env.development?
    return true
  end

  def handle_unverified_request
    raise(ActionController::InvalidAuthenticityToken)
  end

  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find_by_id(session[:user_id]) if session[:user_id]
  end
end

app/controllers/game_controller.rb
class GameController < ApplicationController

  # Initialize a new game.
  def begin_game
    session[:score] = 0
    session[:roundsRemaining] = 10
    session[:streak] = 0
    redirect_to '/game/begin_round'
  end

  def end_game
    Score.create(user_id: current_user.id,
                 value: session[:score],
                 created_at: Time.now())
  end

  # Initialize a new round and start its timer. Return names, photos for the round.
  def begin_round
    if session[:roundsRemaining] == 0
      redirect_to '/game/end_game'
      return
    end

    people = Person.where(user_id: current_user.id)
    needle = people[rand(people.size)]
    all_except_needle = people.collect { |p| p unless p.id == needle.id }.compact.shuffle
    haystack = all_except_needle.sample(4)

    @ids = [ needle.id ]
    @names = {}
    @names[needle.id] = needle.name
    @photos = [ needle.photo_url ]

    haystack.each do |h|
      @ids.push h.id
      @names[h.id] = h.name
      photo_person = all_except_needle.find do |p|
        !@ids.include?(p.id) and !@photos.include?(p.photo_url)
      end
      @photos.push photo_person.photo_url
      # Remove the name corresponding to the photo to make sure we don't end up with > 1 correct pair.
      all_except_needle.delete(photo_person)
    end

    # Save the answer in the session because we need to send it back to the client if their response is wrong.
    session[:answer_id] = needle.id
    session[:answer_photo] = needle.photo_url

    @ids.shuffle!
    @photos.shuffle!
  end

  # Evaluate user's answer, update score.
  def eval_answer
    id = params[:id]
    photo = params[:photo]
    correct = false

    if id
      p = Person.find(id)
      correct = p.photo_url == photo
    end

    response = { correct: correct }
    if not correct
      response[:answer] = {
              id: session[:answer_id],
              photo_url: session[:answer_photo]
      }
      session[:streak] = 0
    else
      increase_score
    end
    decrease_rounds_remaining
    render json: response
  end

  # High scores
  def scores
    @scores = Score.order('value desc').first(5)
  end

  helper_method :score, :roundsRemaining

  private
  def increase_score
    session[:score] += 10
    session[:streak] += 1
    # Get 3 correct in a row for a bonus 5 rounds
    if session[:streak] > 2
      session[:roundsRemaining] += 5
      session[:streak] = 0
    end
  end

  def decrease_rounds_remaining
    session[:roundsRemaining] -= 1
  end

  def score
    session[:score]
  end

  def roundsRemaining
    session[:roundsRemaining]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def delete_account
    current_user.authentications.destroy_all
    current_user.persons.destroy_all
    redirect_to signout_path
  end

  helper_method :people_count, :provider

  private

  def people_count
    @people_count = Person.where(user_id: current_user.id).count
  end

  def provider
    @provider = current_user.authentications.first.provider.capitalize
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    auth = request.env["omniauth.auth"]
    user = User.find_from_omniauth(auth) || User.create_with_omniauth(auth)
    session[:user_id] = user.id
    redirect_to root_url, :notice => "Signed in!"
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Signed out!"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  FACEBOOK = 0
  LINKEDIN = 1
  TWITTER = 2
  SALESFORCE = 3
end

app/views/game/begin_round.html.erb
<div class="status row">
  <span class="span2">
    <div class="score value"><%= score %></div>
    <div class="label">Score</div>
  </span>
  <span class="span2">
    <div class="round value">10</div>
    <div class="label">Time remaining in round (sec)</div>
  </span>
  <span class="span2">
    <div class="game value"><%= roundsRemaining %></div>
    <div class="label">Rounds remaining in game</div>
  </span>
  <span class="span2 result"></span>
  <span class="span4 info"></span>
</div>

<div class="gameboard-container">
  <div class="gameboard">

    <div class="game-input">
      <div class="photos btn-group row" data-toggle="buttons-radio">
        <% @photos.each do |p| %>
        <button class="btn span2" data-action="select-photo"><img src="<%= p %>" /></button>
        <% end %>
      </div>

      <div class="names btn-group row" data-toggle="buttons-radio">
        <% @ids.each do |id| %>
        <button class="btn span2" data-action="select-name" data-id="<%= id %>"><%= @names[id] %></button>
        <% end %>
      </div>
    </div>
  </div>

  <div class="business-cat hidden">
    <img class="taunt" src="" />
  </div>
</div>

app/views/game/end_game.html.erb
<div class="body well">
  <small>Game Over</small>
  <h1>Your score: <%= score %></h1>

  <a href="/">&lsaquo; Home</a> | <a href="/game/scores">High Scores</a>

  <div class="business-cat">
    <%= image_tag 'home.jpg'%>
  </div>
</div>

app/views/game/scores.html.erb
<div class="container scores">
  <div class="container-fluid">

    <div class="page-header">
      <h1>High Scores</h1>
    </div>
    <small><a href="/">&lsaquo; Home</a></small>

    <table class="table table-striped">
    <% @scores.each do |s| %>
      <tr>
        <td><img src="<%= s.user.photo_url %>" /></td>
        <td><h3><%= s.user.name %></h3></td>
        <td><h3><%= s.value %></h3></td>
        <td><%= s.created_at.strftime("%m/%d/%Y") %></td>
      </tr>
    <% end %>
    </table>
  </div>
</div>

app/views/home/index.html.erb
<a href="https://github.com/jmouel/socialnamegame"><img style="position: absolute; top: 0; left: 0; border: 0;" src="https://s3.amazonaws.com/github/ribbons/forkme_left_gray_6d6d6d.png" alt="Fork me on GitHub"></a>

<div class="hero-unit centered">
  <h1>Social Name Game</h1>

  <p>
    This is a sample app built for <a href="http://www.salesforce.com/dreamforce/DF12/">Dreamforce 2012</a>.
    It retrieves your contacts (up to 500) from Twitter, Facebook, LinkedIn, or Salesforce and their
    the names and photos to test your ability to visually identify them.
  </p>

  <h4>Instructions</h4>
  <ul>
    <li>A game lasts for 10 rounds.</li>
    <li>During each round, a series of 5 random photos and names are shown from your network.</li>
    <li>Only one name/photo pair is correct.</li>
    <li>Identify the correct name/photo pair within 10 seconds and receive 10 points.</li>
    <li>If you make 3 correct selections in a row, you receive a bonus 5 rounds.</li>
    <li>At least 100 contacts are required to play the game.</li>
  </ul>

  <div class="body well">
    <% if current_user %>
      <%= image_tag current_user.photo_url %> <%= current_user.name %>
      <%= link_to "[Sign out]", signout_path %>
      <%= link_to "[Delete account]", delete_account_path %>

      <div class="db-info">
        Your game contains <%= people_count %> of your contacts from <%= provider %>.<br />(Only contacts with photos and names are included)
      </div>

      <% if people_count < 100 %>
        <div class="error">You need at least 100 contacts to play the game.</div>
      <% else %>
      <div class="play">
        <button class="btn btn-success btn-large" onclick="window.location='/game/begin_game'">Begin Game!</button>
      </div>
      <% end %>
    <% else %>
      <div class="signin">
        <span>Sign in with:</span>
        <a href="/auth/twitter"><i class="twitter-provider-logo"></i></a>
        <a href="/auth/facebook"><i class="facebook-provider-logo"></i></a>
        <a href="/auth/linkedin"> <i class="linkedin-provider-logo"></i></a>
        <a href="/auth/salesforce"><i class="salesforce-provider-logo"></i></a>
      </div>
    <% end %>

  </div>

  <h4><a href="/game/scores">High Scores</a></h4>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Social Name Game</title>
  <%= csrf_meta_tags %>

  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->

  <%= stylesheet_link_tag "application", :media => "all" %>
</head>
<body>
<%= yield %>
<%= javascript_include_tag "application" %>
</body>
</html>